<?php
namespace MUM\BjrFreizeitFeadmin\Controller;

/***************************************************************
 *  Copyright notice
 *
 *  (c) 2016 Manfred Ursprung <manfred@manfred-ursprung.de>, Webapplikationen Ursprung
 *  
 *  All rights reserved
 *
 *  This script is part of the TYPO3 project. The TYPO3 project is
 *  free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  The GNU General Public License can be found at
 *  http://www.gnu.org/copyleft/gpl.html.
 *
 *  This script is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  This copyright notice MUST APPEAR in all copies of the script!
 ***************************************************************/
//use TYPO3\CMS\Belog\Controller\AbstractController;
use \MUM\BjrFreizeit\Domain\Repository\TagsRepository;
use \MUM\BjrFreizeit\Domain\Model\Tags ;

/**
 *
 *
 * @package bjr_freizeitfeadmin
 * @license http://www.gnu.org/licenses/gpl.html GNU General Public License, version 3 or later
 *
 */
class TagsController extends \MUM\BjrFreizeitFeadmin\Controller\AbstractController {

	/**
	 * tagsRepository
	 *
	 * @var \MUM\BjrFreizeit\Domain\Repository\TagsRepository
     * @inject
	 */
	protected $tagsRepository;


    public function initializeAction()
    {
        //parent::initializeAction(); // TODO: Change the autogenerated stub
        $css = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extRelPath($this->request->getControllerExtensionKey())
            .'Resources/Public/Css/bjrfreizeitfeadmin.css';
        /**  */
        $GLOBALS['TSFE']->getPageRenderer()->addCssFile($css);
    }

    /**
	 * action list
	 *
	 * @return void
	 */
	public function listAction() {

		$tags = $this->tagsRepository->findAll();
        $js = $this->jsForDeleteTag();
        $GLOBALS['TSFE']->getPageRenderer()->addJsFooterInlineCode('tagDelete', $js, false);

        $msg = $GLOBALS['TSFE']->fe_user->getKey("ses","tagChange");
        if(!empty($msg)){
            $this->setFlashMessage($msg);
        }
        $this->view->assign('tags', $tags);
	}

    /**
     * @param \MUM\BjrFreizeit\Domain\Model\Tags $tags
     * @return void
     */
    public function editAction(\MUM\BjrFreizeit\Domain\Model\Tags $tags) {

        $this->view->assign('tags', $tags);
	}


    /**
     * @param \MUM\BjrFreizeit\Domain\Model\Tags $tag
     *
     */
    public function newAction(\MUM\BjrFreizeit\Domain\Model\Tags $tags = NULL){

        $this->view->assign('tags', $tags);

    }


    /**
     * action update
     * @param \MUM\BjrFreizeit\Domain\Model\Tags $tags
     * @return void
     *
     */
    public function updateAction(\MUM\BjrFreizeit\Domain\Model\Tags $tags) {
        $redirectParams = array();  //array('passwordChange' => '',    'organization' => $organization,'organizationChange' => ''       );
        $args = $this->request->getArguments();

        if($tags->_isNew() || $tags->_isDirty()){

            if($tags->_isNew()){
                $tags->setPid($this->settings['pidOrganizationFolder']);

                $this->tagsRepository->add($tags);
                //it is not persistent already, we have to do it!
                $persistenceManager = $this->objectManager->get('TYPO3\\CMS\\Extbase\\Persistence\\Generic\\PersistenceManager');
                $persistenceManager->persistAll();
                //now organization ist persistent
                $GLOBALS['TSFE']->fe_user->setKey("ses","tagChange",'Der Tag <strong>'. $tags->getName() .'</strong> wurde neu angelegt.');
            }else{
                $this->tagsRepository->update($tags);
                $GLOBALS['TSFE']->fe_user->setKey("ses","tagChange",'Der Tag <strong>'. $tags->getName() .'</strong> wurde geändert.');
            }

        }
        $redirectParams['tags'] = $tags;
        $this->redirect('successUpdate', 'Tags', NULL, $redirectParams);


    }


    /**
     * @param \MUM\BjrFreizeit\Domain\Model\Tags $tag
     *
     *
     */
    public function successUpdateAction(\MUM\BjrFreizeit\Domain\Model\Tags $tags){

        $msg = $GLOBALS['TSFE']->fe_user->getKey("ses","tagChange");
        $this->setFlashMessage($msg);
        $this->view->assign('tag',$tags);
    }


    /**
     * @return string
     * per Ajax aufgerufen.
     */
    public function deleteAction() {
        $args = $this->request->getArguments();
        $tag = $this->tagsRepository->findByUid($args['tags']);
        if(is_a($tag, '\MUM\BjrFreizeit\Domain\Model\Tags')) {
            $tagName = $tag->getName();

            $this->tagsRepository->remove($tag);
            $persistenceManager = $this->objectManager->get('TYPO3\\CMS\\Extbase\\Persistence\\Generic\\PersistenceManager');
            $persistenceManager->persistAll();
            $GLOBALS['TSFE']->fe_user->setKey("ses","tagChange",'Die Ferienzeit '. $tagName .' ist gelöscht.');
            //return 'Ferienzeit ' . $name .' is
        }else{
            $GLOBALS['TSFE']->fe_user->setKey("ses","tagChange",'Die Ferienzeit mit der ID '. $args['tags'] .' wurde nicht gefunden.');
        }
        $this->redirect('list', 'Tags');
    }


    protected function jsForDeleteTag(){
        $js = <<<EOT

        $(document).ready(function(){
            var pageId = $('#currentPageId').val();
            $("#dialog").dialog({
                autoOpen: false,
                modal: true,
                show: true,
                buttons : [
                {
                    text: 'Ja',
                    click : function() {
                        var region = $('#dialog').data('regionuid');
                        $.ajax({
                            async: 'true',
                            url: 'index.php',
                            type: 'POST',
                            data: {
                                eID: "bjrfeadmin",
                                request: {
                                    pluginName:  'Region',
                                    controller:  'Region',
                                    action:      'delete',
                                    arguments: {
                                        'pageId': pageId,
                                        'region': region
                                    }
                                }

                            },
                            //dataType: "json",
                            dataType: 'html',

                            success: function(result) {
                                window.location.reload();

                            },
                            error: function(error) {
                                //console.log(error);

                            }
                        });

                    }
                },
                {
                    text: 'Abbrechen',
                    click: function() {
                        $(this).dialog("close");
                    }
                } ]
            });

            $(".callDeleteConfirm").on("click", function(e) {
                e.preventDefault();
                var region = $(this).data('name');
                $('#dialog').data('regionuid', $(this).data('uid'));
                $('#dialog').html('Sind sie sicher, dass die Region "' + region +'" gelöscht werden soll?');
                $("#dialog").dialog("open");
            });




        });


EOT;
        return $js;

    }

}
?>