<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "bjr_freizeit"
 *
 * Auto generated by Extension Builder 2016-02-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Freizeiten anzeigen',
	'description' => 'Listen und Suchen von Freizeiten',
	'category' => 'plugin',
	'author' => 'Manfred Ursprung',
	'author_email' => 'manfred@manfred-ursprung.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.9.7',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);