<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "bjr_lend"
 *
 * Auto generated by Extension Builder 2014-03-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Ausleih Datenbank',
	'description' => 'Verwalten von Artikeln und Ausleihstellen',
	'category' => 'plugin',
	'author' => 'Manfred Ursprung',
	'author_email' => 'manfred@manfred-ursprung.de',
	'author_company' => 'Webapplikationen Ursprung',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.9.6',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>